org: sjm34
app: meter-anomaly-cron
service: meter-anomaly-cron

frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    EMCS_API_KEY: ${param:emcs-api-key}

functions:
  cronHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every top of the hour
      - schedule: cron(0 * ? * * *)
