org: sjm34
app: meter-anomaly-cron
service: meter-anomaly-cron

frameworkVersion: '3'


provider:
  name: aws
  runtime: nodejs14.x

functions:
  rateHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)
  cronHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every 2nd minute from Mon-Fri
      - schedule: cron(0/2 * ? * MON-FRI *)
