org: sjm34
app: meter-anomaly-cron
service: meter-anomaly-cron

frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-offline
custom:
  SECRET_TOKEN: ${sls:stage}-${param:SECRET_TOKEN, 'yqiOpWb6095s097Roybo2793yHXGNWFx6oWCVvvv'}
provider:
  name: aws
  runtime: nodejs14.x
  environment:
    EMCS_API_KEY: ${param:emcs-api-key}
    SECRET_TOKEN: ${self:custom.SECRET_TOKEN}
    PORTAL_API_URL: 'https://portal-api.emcs.cucloud.net/'
    FUNCTION_BASE: ${param:FUNCTION_BASE, 'meter-anomaly-cron-${sls:stage}-'}
functions:
  cronHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every top of the hour
      - schedule: cron(0 * ? * * *)
  testTemplateHandler:
    handler: testTemplate/handler.run
