org: sjm34
app: meter-anomaly-cron
service: meter-anomaly-cron

frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-offline
provider:
  name: aws
  runtime: nodejs16.x
  environment:
    EMCS_API_KEY: ${param:emcs-api-key}
    PORTAL_API_URL: 'https://portal-api.emcs.cucloud.net/'
    FUNCTION_BASE: ${param:FUNCTION_BASE, '${self:app}-${sls:stage}-'}
functions:
  cronHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every top of the hour
      - schedule: cron(0 * ? * * *)
  testTemplateHandler:
    handler: testTemplate/handler.run
