AWSTemplateFormatVersion: 2010-09-09
Description: >-
  meter-anomaly-cron-stack

Transform:
- AWS::Serverless-2016-10-31

Resources:  
  MeterAnomalyTS:
    Type: AWS::Serverless::Application
    Properties:
      Location: ts_src/template.yaml
  MeterAnomalyPY:
    Type: AWS::Serverless::Application
    Properties:
      Location: py_src/template.yaml
Globals:
  Function:
    Environment:
      Variables:
        PORTAL_API_URL:
          Ref: APIURLParameter
        EMCS_API_KEY:
          Ref: EMCSAPIKEYParameter
        SAM_STAGE:
          Ref: StageParameter
Parameters:
  EMCSAPIKEYParameter:
    Type: String
  StageParameter:
    Type: String
  APIURLParameter:
    Type: String